### ISSUE TITLE
Weird behavior: Updates/inserts being routed to slave

### ISSUE THREAD

**Issue by ashu210890** [ankane/distribute_reads#11]
We configured distributed reads in our PostgresQL master slave setup with Ruby on Rails app and PGBouncer sitting on top of each of the Postgres instances. We are using the following settings in our database.yml

```
production:
  adapter: postgresql_makara
  encoding: utf8
  database: <db_name>
  pool: 500
  username: <user_name>
  prepared_statements: false
  reaping_frequency: 10
  connect_timeout: 5
  checkout_timeout: 5
  variables:
    statement_timeout: 600000
  makara:
    sticky: true
    connections:
      - role: master
        name: postgres-prod-1
        host: postgres-prod-1
        port: <pg_bouncer_port>
      - role: slave
        name: postgres-prod-2
        host: postgres-prod-2
        port: <pg_bouncer_port>
```

We have put exactly one method under `distribute_reads {}` block which we are sure does not do any `SET/UPDATE/INSERT` operations. However, we are constantly seeing error like ` ERROR:  cannot execute UPDATE in a read-only transaction` in our slave's postgresql logs.

Are we missing something in the config?
