### ISSUE TITLE
Specifying the name of the replica with the distribute_reads method

### ISSUE THREAD

**Issue by fabienpiette** [ankane/distribute_reads#37]
Hello,

With the configuration below, is it possible to specify the name of the replica used when calling the distribute_reads method? The idea is to be able to choose on which replica I want to make SELECT queries.

Something like this:
```
distribute_reads(replica1: true) do
  # ...
end
```
or
```
distribute_reads(name: 'replica1') do
  # ...
end
```

```
default: &default
  url: postgresql-makara:///
  makara:
    sticky: true
    connections:
      - role: master
        name: primary
        url: <%= ENV["DATABASE_URL"] %>
      - name: replica1
        url: <%= ENV["REPLICA1_DATABASE_URL"] %>
      - name: replica2
        url: <%= ENV["REPLICA2_DATABASE_URL"] %>

development:
  <<: *default

production:
  <<: *default
```

Thank you in advance for your answers.
